// Data model for a single journal entry (trip log) attached to a province.
export interface JournalEntry {
  id: string;
  provinceId: string;
  date: string; // ISO date string, e.g. "2026-09-12"
  title: string;
  notes: string;
  photoUris: string[];
  tags: string[];
  // Sync metadata added in the Landmark & Supabase Integration round (T34).
  // Optional so v1 call sites/tests that construct entries without these
  // fields keep compiling — db.ts always fills them in with defaults.
  /** ISO timestamp of the last local edit. Drives last-write-wins (T40). */
  updatedAt?: string;
  /** ISO timestamp of the last successful sync to Supabase, or null/undefined if never synced. */
  syncedAt?: string | null;
  /** Row id on the Supabase side once synced at least once, or null/undefined. */
  cloudId?: string | null;
  /** Consecutive sync failure count for this record (drives the "retry-issue" badge, T39/T51). */
  retryCount?: number;
}

// Shape used when creating a new entry (id is generated by storage layer).
export type NewJournalEntry = Omit<JournalEntry, 'id'>;
