// US-27 (รอบ 13) — builds a lean, uncapped search index from the TAT
// attraction catalog, separate from the small curated "top picks" list in
// thailand-landmarks.ts.
//
// *** Dev/build-time tool ONLY. Never fetches from the network at app
// runtime — this generates a static file that gets bundled. Run it by hand: ***
//
//   node scripts/extract-tat-search-index.ts
//
// Why a separate file instead of just raising MAX_LANDMARKS_PER_PROVINCE in
// scripts/lib/tat-extract-core.ts: no field in the TAT dataset reliably
// signals real-world notability (verified by hand — see
// buildSearchIndexEntries's docstring for the concrete หาดชะอำ/Cha-am Beach
// case that motivated this). Any capped "top N" heuristic silently drops
// well-known places at random. The curated list stays small and capped
// (good for a "recommended for this province" card grid); this file is
// large and uncapped (every valid record for every non-pilot,
// non-empty-fixture province) so *search* — the thing users actually
// complained didn't find real places — draws from the full set.
//
// Unlike scripts/merge-landmarks.ts (which incrementally APPENDS into
// thailand-landmarks.ts, batch after batch, forever), this file is fully
// REGENERATED from scratch every run — it has no history to preserve, no
// user check-in state ever keys off any id in it (it's search-only, never
// rendered as a checkin-able card), so overwriting it whole is safe and
// simpler than an incremental merge.
import fs from 'node:fs';
import { PROVINCES } from '../src/data/thailand-provinces.ts';
import { buildSearchIndexEntries, type TatRawRecord } from './lib/tat-extract-core.ts';

const TAT_DATASET_URL =
  'https://datacatalog.tat.or.th/dataset/87442079-88ec-42eb-b507-dcf135fc4301/resource/9348705e-18b4-4815-8d2c-0fd2f649e88e/download/attraction.json';
const USER_AGENT = 'THAITRIP-dev-extraction-script/1.0 (contact: phumrapee47@gmail.com)';
const OUT_FILE = 'src/data/tat-search-index.ts';

// Same two exclusion sets as scripts/extract-tat-landmarks.ts, for the same
// reasons (see that file's header comment) — kept as separate literals here
// too, deliberately not imported, so each script has zero dependency on the
// others' shape.
const PILOT_PROVINCE_IDS: ReadonlySet<string> = new Set([
  'bangkok-metropolis',
  'chiang-mai',
  'chiang-rai',
  'phra-nakhon-si-ayutthaya',
  'sukhothai',
  'chon-buri',
  'krabi',
  'phuket',
]);
const KEEP_EMPTY_PROVINCE_IDS: ReadonlySet<string> = new Set(['chaiyaphum', 'si-sa-ket']);

async function fetchTatRecords(): Promise<TatRawRecord[]> {
  const res = await fetch(TAT_DATASET_URL, { headers: { 'User-Agent': USER_AGENT } });
  if (!res.ok) throw new Error(`TAT dataset request failed with HTTP ${res.status}`);
  const data = await res.json();
  const key = Object.keys(data)[0];
  const records = data[key];
  if (!Array.isArray(records)) throw new Error('Unexpected TAT dataset shape: expected an array of records');
  return records as TatRawRecord[];
}

function formatEntryLiteral(l: { id: string; provinceId: string; nameTh: string; lat: number; lng: number }): string {
  const round = (n: number) => Math.round(n * 1e7) / 1e7;
  return `  { id: ${JSON.stringify(l.id)}, provinceId: ${JSON.stringify(l.provinceId)}, nameTh: ${JSON.stringify(l.nameTh)}, lat: ${round(l.lat)}, lng: ${round(l.lng)} },`;
}

async function main(): Promise<void> {
  const targets = PROVINCES.filter(
    (p) => !PILOT_PROVINCE_IDS.has(p.id) && !KEEP_EMPTY_PROVINCE_IDS.has(p.id)
  );
  console.log(`[extract-tat-search-index] ${targets.length} target province(s), uncapped.`);

  console.log('[extract-tat-search-index] Downloading TAT attraction catalog (~32MB)...');
  const records = await fetchTatRecords();
  console.log(`[extract-tat-search-index] Downloaded ${records.length} raw record(s).`);

  const byProvinceName = new Map<string, TatRawRecord[]>();
  for (const record of records) {
    const name = record.PROVINCE_NAME_TH;
    if (!name) continue;
    if (!byProvinceName.has(name)) byProvinceName.set(name, []);
    byProvinceName.get(name)!.push(record);
  }

  const lines: string[] = [];
  let total = 0;
  for (const province of targets) {
    const raw = byProvinceName.get(province.nameTh) ?? [];
    const entries = buildSearchIndexEntries(province.id, raw);
    if (entries.length === 0) continue;
    total += entries.length;
    lines.push(`\n  // ${province.nameTh} (${province.id})`);
    for (const e of entries) lines.push(formatEntryLiteral(e));
  }

  const fileContent = `// AUTO-GENERATED by scripts/extract-tat-search-index.ts — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/extract-tat-search-index.ts
//
// US-27 (รอบ 13): a lean, uncapped search index built from the TAT
// attraction catalog (https://datacatalog.tat.or.th) — every valid record
// for every non-pilot, non-empty-fixture province, not just the small
// curated "top picks" list in thailand-landmarks.ts. Search-only: never
// rendered as a checkin-able card, so no user check-in state ever keys off
// any id here, and this file can be safely regenerated/overwritten whole.
import type { Landmark } from './thailand-landmarks';

export const TAT_SEARCH_INDEX: Landmark[] = [${lines.join('\n')}
];
`;

  fs.writeFileSync(OUT_FILE, fileContent, 'utf8');
  console.log(`[extract-tat-search-index] Wrote ${total} entries across ${targets.length} province(s) to ${OUT_FILE}.`);
}

main().catch((err) => {
  console.error('[extract-tat-search-index] fatal error:', err);
  process.exitCode = 1;
});
